// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkSVzFxzVMOrWovBeM1JV4-FQjEH7MohY',
    appId: '1:957671811855:web:24622829dc2a9e4032ac7a',
    messagingSenderId: '957671811855',
    projectId: 'derasoft-ass1',
    authDomain: 'derasoft-ass1.firebaseapp.com',
    storageBucket: 'derasoft-ass1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd_IedFJQyv0iESxObePeUg-1OQLx0yQ4',
    appId: '1:957671811855:android:73394540cbc667f132ac7a',
    messagingSenderId: '957671811855',
    projectId: 'derasoft-ass1',
    storageBucket: 'derasoft-ass1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhAWpU4Thq8II62mVXXFaFuVSz7EZtTc',
    appId: '1:957671811855:ios:652b0d355c5602ca32ac7a',
    messagingSenderId: '957671811855',
    projectId: 'derasoft-ass1',
    storageBucket: 'derasoft-ass1.appspot.com',
    iosBundleId: 'com.example.internshipVuagao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhAWpU4Thq8II62mVXXFaFuVSz7EZtTc',
    appId: '1:957671811855:ios:ba005d973d93895b32ac7a',
    messagingSenderId: '957671811855',
    projectId: 'derasoft-ass1',
    storageBucket: 'derasoft-ass1.appspot.com',
    iosBundleId: 'com.example.internshipVuagao.RunnerTests',
  );
}
